version: '3.9'

services:
  db:
    image: postgres:17.5
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgres

  app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: